cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

online_supermarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [



    path('online-supermarket.com/', include('store.urls', namespace='store')),
    path('about/', include('webdes.urls', namespace='webdes')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('admin/', admin.site.urls),


    # path('payment/', include('payment.urls', namespace='payment')),








]













if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
admin.site.index_title = 'Online-Supermarket'
admin.site.site_title = 'Online-Supermarket'
admin.site.site_header = 'Online-Supermarket'

store/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
	path('', views.product_list, name='product_list'),
	path('search/', views.product_search, name='search'),
	path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

	]

webdes/urls.py
from django.urls import path
from . import views

app_name = 'webdes'

urlpatterns = [
	path('', views.aboutpage, name='webdes_detail'),
]

templates/banner.html

{% load static %}
<div class="banner">
	<div class="banner-left col-3">
		<h1 class="company-logo">Online Supermarket</h1>
		<i class="fa fa-shoe-prints fa-5x c-defaolt"></i>
		<!--i class="fa fa-cat fa-5x "  style="color: #FFF;"></i-->
		<p class="company-moto mt-5">online supermarket</p>
	</div>
	<div class="banner-right col-9" style="background-image: url({% static 'pics/banner.jpeg' %}); background-repeat: no-repeat; background-size: cover;">
		<h1 class="company-name">ONLINE SUPERMARKET Adama</h1>
		<a href=""><i class=" fa fa-cat fa-2x c-w cat"></i></a>
		<div class="banner-pic ml-5 ">
			<!-- <img src="{% static 'pics/.jpg' %}" class="pic-circle"> -->
		</div>
	</div>
</div>
<div class="mid-nav">
	<a {% if not category %}class='active'{% endif %} href="{% url 'store:product_list' %}">All</a>
	{% for c in categories %}
		<a {% if category.slug == c.slug %}class='active'{% endif %}  href="{{ c.get_absolute_url }}">
			{{ c.name }} 
		</a>
	{% endfor %}
	

</div>


templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/store.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free-5.15.1-web/css/all.min.css' %}">
	
</head>
<body>
	<nav class="navbar" id="myNavbar">
		<a {% if not category %}class='active'{% endif %} href="{% url 'store:product_list' %}">
			<i class="fa fa-fw fa-home"></i>Home
		</a>
		<a href="#search"><i class="fa fa-fw fa-search"></i> Search</a>
		<a href="#"><i class="fa fa-fw fa-envelope"></i> Contact</a>
		<a href="#"><i class="fa fa-fw fa-newspaper"></i> News</a>
		<a href="{% url 'webdes:webdes_detail' %}"><i class="fa fa-fw fa-blog"></i>About</a>
		<a href="#">
			<form method="get" action="{% url 'store:search' %}">
				
				<input type="search" class="c-b" name="query" id="search" placeholder="Search" required="">
				<button type="submit">search
				</button>
			</form>
		<span class="float-r mr-5">
			<a href="{% url 'cart:cart_detail' %}">
				<i class="fa fa-shopping-cart "></i>
				<!--i class="fa fa-shopping-bag "></i-->
				{% with total_items=cart|length %}
					{% if total_items > 0 %}
						<span class="pric">
							{{ total_items }}, 
							${{ cart.get_total_price }}
						</span>
							
						
					{% else %}
					{% endif %}
				{% endwith %}
			</a>
		</span>
		<a href="javascript:void(0);" class="icon float-r" onclick="navbarToggler()">
			<i class="fa fa-bars"></i>
			
		</a>
	</nav>
	<div class="progress-container" id="progress-bar">
		<div class="progress-bar" id="myBar"></div>
	</div> 
	<div class="contianer">
		{% block banner_content %}
		
		{% endblock %}
		<div class="row ">
			<div class=" col-2 col-sm-2">
				{% block left_side_content %} 
				{% endblock %}
			</div>
			<div class="main-cont col-8 col-sm-12" id="product_list">
				{% block main_content %} 
				{% endblock %}	
				{% block form_content %}
				{% endblock %}
			</div>
			<div class=" col-2 col-sm-2">
				{% block right_side_content %} 
				{% endblock %}
			</div>
		</div>

		{% block footer_content %}
		{% endblock %}

	</div>

	<script src="{% static 'jquery-3.5.1/jquery-3.5.1.js' %}"></script>
	<script>

		$(document).ready(function()
		{
			{% block domready %}
			{% endblock %}
		});
		

	</script>
	
	<script type="text/javascript" src="{% static 'js/store.js' %}"></script>
</body>
</html>

templates/footer.html
  
<footer>
	<div class="footer">
		<div class="catagory col-4 pl-5">
			<h3 class="footer-h">Category</h3>
			<a href="{% url 'store:product_list' %}">All</a>
			{% for c in categories %}
				<a {% if category.slug == c.slug %}class='active'{% endif %}  href="{{ c.get_absolute_url }}">
					{{ c.name }} 
				</a>
			{% endfor %}	
		</div>
		<div class="custumer-s col-4 pl-5">
			<h3 class="footer-h">Contact</h3>
			<i class="fa fa-2x fa-headset"></i><br><br>
			<i class="fa fa-phone">+251234567890</i>
		</div>
		<div class="contact col-4 pl-5">
			<h3 class="footer-h">Social</h3>
	
			<a href="" target="_break" class="links-d linkedin ">
				<i class="pointer pl-3  fab fa-linkedin"></i>
			</a>
			<a href="" target="_break" class="links-d twitter ">
				<i class="pointer pl-3  fab fa-twitter"></i>
			</a>
			<a href="" target="_break" class="links-d telegram">
				<i class="pointer pl-3  fab fab fa-telegram"></i>
			</a>
			<a href="" target="_break" class="links-d instagram">
				<i class="pointer pl-3  fab fa-instagram"></i>
			</a>
			<a href="" target="_break" class="links-d facebook"><i class="pointer pl-3  fab fa-facebook"> </i> 
			</a>
		</div>
	</div>
	<div class="copyright"> 
		<span class="c-r"> Online Supermarket </span> 
		<div class="copyright align-c">
			 7Noon ©<script>document.write(new Date().getFullYear());</script> All rights reserved 
		</div>
		<button onclick="topFunction()" id="myBtn" title="Go to top">Top ^ </button> 
	</div>
</footer>

templates/logint.html
 {% extends 'base.html' %}
  {% block main_content %}
    <div class="main-content">
      <!-- Header -->
      <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
        <div class="container">
          <div class="header-body text-center mb-7">
            <div class="row justify-content-center">
              <div class="col-xl-5 col-lg-6 col-md-8 px-5">
                <h1 class="text-white">Welcome!</h1>
                <p class="text-lead text-white">Use these awesome forms to login or create new account in your project for free.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="separator separator-bottom separator-skew zindex-100">
          <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
            <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
          </svg>
        </div>
      </div>
      <!-- Page content -->
      <div class="container mt--8 pb-5">
        <div class="row justify-content-center">
          <div class="col-lg-5 col-md-7">
            <div class="card bg-secondary border-0 mb-0">
              <div class="card-header bg-transparent pb-5">
                <div class="text-muted text-center mt-2 mb-3"><small>Sign in with</small></div>
                <div class="btn-wrapper text-center">
                  <a href="#" class="btn btn-neutral btn-icon">
                    <span class="btn-inner--icon"><img src="../assets/img/icons/common/github.svg"></span>
                    <span class="btn-inner--text">Github</span>
                  </a>
                  <a href="#" class="btn btn-neutral btn-icon">
                    <span class="btn-inner--icon"><img src="../assets/img/icons/common/google.svg"></span>
                    <span class="btn-inner--text">Google</span>
                  </a>
                </div>
              </div>
              <div class="card-body px-lg-5 py-lg-5">
                <div class="text-center text-muted mb-4">
                  <small>Or sign in with credentials</small>
                </div>
                <form role="form">
                  <div class="form-group mb-3">
                    <div class="input-group input-group-merge input-group-alternative">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                      </div>
                      <input class="form-control" placeholder="Email" type="email">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="input-group input-group-merge input-group-alternative">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                      </div>
                      <input class="form-control" placeholder="Password" type="password">
                    </div>
                  </div>
                  <div class="custom-control custom-control-alternative custom-checkbox">
                    <input class="custom-control-input" id=" customCheckLogin" type="checkbox">
                    <label class="custom-control-label" for=" customCheckLogin">
                      <span class="text-muted">Remember me</span>
                    </label>
                  </div>
                  <div class="text-center">
                    <button type="button" class="btn btn-primary my-4">Sign in</button>
                  </div>
                </form>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-6">
                <a href="#" class="text-light"><small>Forgot password?</small></a>
              </div>
              <div class="col-6 text-right">
                <a href="#" class="text-light"><small>Create new account</small></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}